spring:
  application:
    name: fitmetric
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:database
    username: 
    password: 
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 20

server:
  port: 5000
  address: 0.0.0.0

jwt:
  secret: "Your secret jwt key "
  expiration: 86400000

gemini:
  api:
    key: api-key
    url: 
    model: model
    max-retries: 3
    timeout-seconds: 30
    temperature: 0.7
    max-tokens: 2048

logging:
  level:
    com.fitmetric: DEBUG
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
