package com.fitmetric.dto.response;

import lombok.Builder;
import lombok.Data;
import java.util.List;

/**
 * AI-generated health insight response.
 *
 * Contains personalized health recommendations and analysis
 * generated by the Gemini AI based on user data.
 */
@Data
@Builder
public class HealthInsightResponse {
    private String category;
    private String title;
    private String description;
    private String impact;
    private List<SourceDto> sources;

    @Data
    @Builder
    public static class SourceDto {
        private String uri;
        private String title;
    }
}